# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g selenium-side-runner
    - run: npm install -g chromedriver
    - run: |
              VERSION_STRING="88.0.4324.96-1"
              wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${VERSION_STRING}_amd64.deb"
              sudo dpkg -i "google-chrome-stable_${VERSION_STRING}_amd64.deb"
    - run: selenium-side-runner -c "chromeOptions.args=[disable-infobars, headless, no-sandbox]" sems-sat-*.side
