name: Selenium tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        npm install -g selenium-side-runner
        npm install -g chromedriver
    
    - name: Run tests
      run: |
        selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless=new]" sems-sat-side2.side
